### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by nealmcb** [terrycojones/describejson#1]
This is such a handy utility. Thank you!
But without a license, we don't know if we can really use it, or would want to contribute to it, vs other similar projects like https://github.com/pgbovine/json-summarizer

I recommend this as a useful source of licensing help: [Choosing an Open Source License](https://github.com/blog/1530-choosing-an-open-source-license)

At any rate, thanks again.

**Comment by terrycojones** [comment]
Hey Neal. I'll add a License. Thanks!

**Comment by terrycojones** [comment]
OK, done. Thanks again!
